# Site settings
title: GeoAPI Documentation
email: contact@beta.gouv.fr
documentation: http://192.168.1.19:4567/
description: > #
 La GéoAPI est une boîte-à-outils
 facile à prendre en main pour rendre vos applications
  et bases de données plus intelligentes, en terme de positionnement
  et de connaissance des territoires.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sgmap.github.io/geoapi-doc/" # the base hostname & protocol for your site
github_repository: "https://github.com/sgmap/geoapi-doc"

# Build settings
markdown: kramdown

collections:
  calls:
    output: true
