version: 2

defaults:
  workspace_root: &workspace_root
    ~/geoapigouv

  nodejs_container: &nodejs_container
    working_directory: *workspace_root
    docker:
      - image: circleci/node:8-stretch

  filters: &default_filters
    tags:
      only: '/v[0-9]+(\.[0-9]+)*/'

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  restore_node_modules: &restore_node_modules
    restore_cache:
      name: Restore node_modules cache
      keys:
        - v1-geoapigouv-node-{{ checksum "yarn.lock" }}
        - v1-geoapigouv-node-

jobs:
  checkout:
    <<: *nodejs_container
    steps:
      - checkout

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - ./

  install:
    <<: *nodejs_container
    steps:
      - *attach_workspace
      - *restore_node_modules

      - restore_cache:
          name: Restore yarn cache
          keys:
            - v1-geoapigouv-yarn-{{ checksum "yarn.lock" }}
            - v1-geoapigouv-yarn-

      - run:
          name: Install dependencies
          command: yarn

      - save_cache:
          name: Save yarn cache
          key: v1-geoapigouv-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn/

      - save_cache:
          name: Save node_modules cache
          key: v1-geoapigouv-node-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/

  lint:
    <<: *nodejs_container
    steps:
      - *attach_workspace
      - *restore_node_modules

      - run:
          name: Lint JavaScript
          command: yarn lint

  test:
    <<: *nodejs_container
    steps:
      - *attach_workspace
      - *restore_node_modules

      - run:
          name: Run tests
          command: yarn test

      - store_test_results:
          path: reports/tests/

      - run:
          name: Upload code coverage to codecov
          command: yarn codecov

  build:
    <<: *nodejs_container
    steps:
      - *attach_workspace
      - *restore_node_modules

      - run:
          name: Build output bundles
          command: yarn build

      - run:
          name: Export bundles as static HTML
          command: yarn export

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .next/
            - out/

      - run:
          name: Extract built bundles for stats
          command: |
            mkdir dist-stats
            cp -r .next/app.js .next/bundles dist-stats
            # Remove _document.js as it’s only used by the server.
            rm dist-stats/bundles/pages/_document.js
            tar cvf dist-stats/chunks.js.tar .next/chunks/*.js
            gzip -r dist-stats

      -  store_artifacts:
          name: Store built bundles for stats
          path: dist-stats

  deploy:
    <<: *nodejs_container
    steps:
      - *attach_workspace
      - *restore_node_modules

      - add_ssh_keys:
          fingerprints:
            - ee:0b:5b:65:1f:52:2a:b3:07:30:53:33:9a:d4:1d:34

      - run:
          name: Setup SSH to GitHub
          command: ssh-keyscan github.com > ~/.ssh/known_hosts

      - run:
          name: Set SSH user email
          command: git config --global user.email "infra@beta.gouv.fr"

      - run:
          name: Set SSH user name
          command: git config --global user.name "CircleCI"

      - deploy:
          name: Deploy to gh-pages branch on GitHub
          command: yarn deploy

workflows:
  version: 2

  build_test_deploy:
    jobs:
      - checkout:
          filters: *default_filters

      - install:
          requires:
            - checkout
          filters: *default_filters

      - lint:
          requires:
            - install
          filters: *default_filters

      - build:
          requires:
            - install
          filters: *default_filters

      - deploy:
          requires:
            - lint
            - build
          filters:
            branches:
              only: next
